public class WordGame {
/*
	private Integer numWords;
    private Integer lengthWords;
    private String targetWord;
    private List<String> lstWords;
    private String selectedWord;
    private Integer numGuess;
    public Static Integer guessCount = 4;

    public void setData(Integer numWords, Integer lengthWords) {
        this.numWords = numWords;
        this.lengthWords = lengthWords;
        numGuess = 0;
    }
    
    public List<String> selectRandomWords() {
        //sObject - words
        Integer count = [Select count() From Words Where Length__c=8]; // 30
        //1 - 30 > generate 10 random numbers - 1,2,3,5,10,15
        List<String> lstWords = [Select Id,Word__c, Length__c From Words Where Length__c=8];
        targetWord = lstWords[3];
        list<String> lstWords = 
    }
    
    public Integer matchinPositions(selectedWord) {
        numGuess >= guessCount : return -1;
        Integer matchesFound = 0;
        for(Integer i=0; i<lengthWords; i++) {
            if(targetWord.charAt(i) == selectedWord.charAt(i)) {
                matchesFound ++;
            }
        }
        numGuess ++;
        return matchesFound;
    }
*/
}